# Generated by Django 5.2.16 on 2026-07-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('es_municipal', models.BooleanField(default=False, help_text='Sedes municipales (Barranca, San Gil, Málaga) usan parametrización propia.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Unidad de negocio',
                'verbose_name_plural': 'Unidades de negocio',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('especialidad', models.CharField(blank=True, max_length=80)),
                ('metodo_calculo', models.CharField(choices=[('POR_HORAS', 'Por horas ÷ tiempo estándar'), ('POR_DIA_SEMANA', 'Por patrón de días de la semana'), ('PERSONALIZADO', 'Personalizado (overrides estructurados)')], default='POR_HORAS', max_length=20)),
                ('atiende_sabados', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas', to='core.sede')),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas', to='core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Sala / ítem',
                'verbose_name_plural': 'Salas / ítems',
                'ordering': ['unidad_negocio', 'orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('unidad_negocio', 'sede', 'nombre', 'especialidad'), name='uniq_sala_por_unidad_sede_nombre')],
            },
        ),
    ]
