# Generated by Django 5.2.16 on 2026-07-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AddField(
            model_name='sede',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
