# Generated by Django 5.2.16 on 2026-07-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('es_nacional', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Festivo',
                'verbose_name_plural': 'Festivos',
                'ordering': ['fecha'],
            },
        ),
    ]
