# Generated by Django 5.2.16 on 2026-07-07 15:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_dia_lav', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas/día L–V')),
                ('horas_dia_sabado', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas/día sábados')),
                ('tiempo_estandar_horas', models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Tiempo estándar (horas)')),
                ('ajuste_sobreatencion', models.IntegerField(default=0, help_text='Citas adicionales por sobreatención (columna I del Excel).', verbose_name='Ajuste por sobreatenciones')),
                ('override_dias_lav', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('override_sabados', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('horario_laboral', models.TextField(blank=True)),
                ('citas_dia_lav', models.IntegerField(default=0, editable=False)),
                ('citas_dia_sabado', models.IntegerField(default=0, editable=False)),
                ('citas_mes', models.IntegerField(default=0, editable=False)),
                ('citas_mes_total', models.IntegerField(default=0, editable=False)),
                ('neto_capacidad_ajustada', models.IntegerField(default=0, editable=False)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='core.sala')),
            ],
            options={
                'verbose_name': 'Capacidad de sala (mes)',
                'verbose_name_plural': 'Capacidades de sala (mes)',
                'ordering': ['parametro', 'sala'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FESTIVO', 'Festivo'), ('INCAPACIDAD', 'Incapacidad'), ('CURSO', 'Curso / capacitación'), ('TEST_EJERCICIO', 'Test de ejercicio'), ('CIERRE_SALA', 'Cierre de sala'), ('SESION_EDUCATIVA', 'Sesión educativa'), ('APOYO_SERVICIO', 'Apoyo a otro servicio'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('signo', models.CharField(choices=[('DESCONTAR', 'Descontar (−)'), ('SUMAR', 'Sumar (+)')], default='DESCONTAR', max_length=10)),
                ('citas_afectadas', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('capacidad_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='capacidad.capacidadsala')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['capacidad_sala', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='ParametroMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('modo', models.CharField(choices=[('CALENDARIO', 'Calendario real (descuenta festivos)'), ('EXCEL_LEGACY', 'Parámetros fijos (fidelidad Excel)')], default='CALENDARIO', max_length=15)),
                ('dias_lav', models.PositiveSmallIntegerField(default=5, verbose_name='# Días Lunes a Viernes')),
                ('sabados_semana', models.PositiveSmallIntegerField(default=1, verbose_name='# Sábados por semana')),
                ('semanas_mes', models.PositiveSmallIntegerField(default=4, verbose_name='# Semanas del mes')),
                ('minutos_hora', models.PositiveSmallIntegerField(default=60, verbose_name='Minutos por hora')),
                ('tiempo_por_cita_min', models.DecimalField(decimal_places=2, default=30, max_digits=6, verbose_name='Tiempo por cita (min)')),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Parámetro mensual',
                'verbose_name_plural': 'Parámetros mensuales',
                'ordering': ['-anio', 'mes', 'unidad_negocio'],
            },
        ),
        migrations.AddField(
            model_name='capacidadsala',
            name='parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='capacidad.parametromensual'),
        ),
        migrations.CreateModel(
            name='PatronDiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=120)),
                ('dias', models.PositiveSmallIntegerField(default=0, verbose_name='# días (conteo fijo)')),
                ('citas_por_dia', models.PositiveIntegerField(default=0)),
                ('es_sabado', models.BooleanField(default=False, help_text='Si es sábado, aporta como total mensual (no se multiplica por semanas).')),
                ('dias_semana', models.CharField(blank=True, help_text='Días de la semana (0=lun..6=dom) separados por coma, para modo calendario.', max_length=20)),
                ('capacidad_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrones', to='capacidad.capacidadsala')),
            ],
            options={
                'verbose_name': 'Patrón día de la semana',
                'verbose_name_plural': 'Patrones día de la semana',
                'ordering': ['capacidad_sala'],
            },
        ),
        migrations.CreateModel(
            name='ResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('meta_atenciones', models.IntegerField(blank=True, null=True)),
                ('atenciones_realizadas', models.IntegerField(default=0)),
                ('valor_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('meta_pct', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Resumen mensual',
                'verbose_name_plural': 'Resúmenes mensuales',
                'ordering': ['-anio', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='TerminoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('citas', models.IntegerField(default=0)),
                ('periodicidad', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='SEMANAL', max_length=10)),
                ('capacidad_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminos', to='capacidad.capacidadsala')),
            ],
            options={
                'verbose_name': 'Término adicional',
                'verbose_name_plural': 'Términos adicionales',
                'ordering': ['capacidad_sala'],
            },
        ),
        migrations.AddConstraint(
            model_name='parametromensual',
            constraint=models.UniqueConstraint(fields=('unidad_negocio', 'anio', 'mes'), name='uniq_parametro_unidad_anio_mes'),
        ),
        migrations.AddConstraint(
            model_name='capacidadsala',
            constraint=models.UniqueConstraint(fields=('sala', 'parametro'), name='uniq_capacidad_sala_parametro'),
        ),
        migrations.AddConstraint(
            model_name='resumenmensual',
            constraint=models.UniqueConstraint(fields=('unidad_negocio', 'anio', 'mes'), name='uniq_resumen_unidad_anio_mes'),
        ),
    ]
