# Generated by Django 5.2.16 on 2026-07-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidadsala',
            name='citas_dom',
            field=models.PositiveIntegerField(default=0, verbose_name='Citas domingo'),
        ),
        migrations.AddField(
            model_name='capacidadsala',
            name='citas_jue',
            field=models.PositiveIntegerField(default=0, verbose_name='Citas jueves'),
        ),
        migrations.AddField(
            model_name='capacidadsala',
            name='citas_lun',
            field=models.PositiveIntegerField(default=0, verbose_name='Citas lunes'),
        ),
        migrations.AddField(
            model_name='capacidadsala',
            name='citas_mar',
            field=models.PositiveIntegerField(default=0, verbose_name='Citas martes'),
        ),
        migrations.AddField(
            model_name='capacidadsala',
            name='citas_mie',
            field=models.PositiveIntegerField(default=0, verbose_name='Citas miércoles'),
        ),
        migrations.AddField(
            model_name='capacidadsala',
            name='citas_sab',
            field=models.PositiveIntegerField(default=0, verbose_name='Citas sábado'),
        ),
        migrations.AddField(
            model_name='capacidadsala',
            name='citas_vie',
            field=models.PositiveIntegerField(default=0, verbose_name='Citas viernes'),
        ),
    ]
