# Generated by Django 5.2.16 on 2026-07-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacidad', '0002_capacidadsala_citas_dom_capacidadsala_citas_jue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidadsala',
            name='sabados_alternos',
            field=models.BooleanField(default=False, help_text='Atiende un sábado sí y uno no (quincenal): cuenta la mitad de los sábados del mes, redondeando hacia abajo.', verbose_name='Sábado de por medio'),
        ),
    ]
