# Generated by Django 5.2.16 on 2026-07-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacidad', '0003_capacidadsala_sabados_alternos'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametromensual',
            name='novedades_abiertas',
            field=models.BooleanField(default=False, help_text='Si está activo, los usuarios pueden registrar novedades de este mes en el módulo de novedades.', verbose_name='Ingreso de novedades habilitado'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='tipo',
            field=models.CharField(choices=[('INCAPACIDAD', 'Incapacidad'), ('PERMISO', 'Permiso'), ('PERMISO_VOTACION', 'Permiso por votación'), ('VACACIONES', 'Vacaciones'), ('CURSO', 'Capacitación aprobada por gerencia'), ('REUNION', 'Reunión autorizada por gerencia'), ('MANTENIMIENTO', 'Mantenimiento autorizado'), ('FESTIVO', 'Festivo'), ('TEST_EJERCICIO', 'Test de ejercicio'), ('CIERRE_SALA', 'Cierre de sala'), ('SESION_EDUCATIVA', 'Sesión educativa'), ('APOYO_SERVICIO', 'Apoyo a otro servicio'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
    ]
