# Generated by Django 5.2.16 on 2026-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacidad', '0007_alter_novedad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='tipo',
            field=models.CharField(choices=[('INCAPACIDAD', 'Incapacidad'), ('PERMISO', 'Permiso'), ('PERMISO_VOTACION', 'Permiso por votación'), ('VACACIONES', 'Vacaciones'), ('CURSO', 'Capacitación aprobada por gerencia'), ('REUNION', 'Reunión autorizada por gerencia'), ('REUNION_GENERAL', 'Reunión'), ('MANTENIMIENTO', 'Mantenimiento autorizado'), ('FESTIVO', 'Festivo'), ('TEST_EJERCICIO', 'Prueba/procedimiento (desplaza consultas)'), ('CIERRE_SALA', 'Cierre de sala'), ('SESION_EDUCATIVA', 'Sesión educativa'), ('APOYO_SERVICIO', 'Apoyo a otro servicio'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
    ]
