# Generated by Django 5.2.16 on 2026-07-29 14:49

import apps.capacidad.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacidad', '0010_tiponovedad_tabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='tipo',
            field=models.ForeignKey(default=apps.capacidad.models._tipo_novedad_otro_pk, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='capacidad.tiponovedad'),
        ),
    ]
