# Generated by Django 5.2.16 on 2026-07-29 16:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacidad', '0011_alter_novedad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumenmensual',
            name='meta_cumplimiento_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.90'), max_digits=5, verbose_name='Meta de cumplimiento'),
        ),
    ]
