# Generated by Django 5.2.16 on 2026-07-10 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_sede_options_sede_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('nombre_normalizado', models.CharField(editable=False, max_length=180, unique=True)),
                ('nit', models.CharField(blank=True, max_length=30)),
                ('creada_automaticamente', models.BooleanField(default=False, help_text='Creada al importar atenciones (no venía en convenios).')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MapeoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=120)),
                ('especialidad_normalizada', models.CharField(editable=False, max_length=120, unique=True)),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades_mapeadas', to='core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Mapeo especialidad → unidad',
                'verbose_name_plural': 'Mapeos especialidad → unidad',
                'ordering': ['especialidad'],
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('anio', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('mes', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('codigo_servicio', models.CharField(db_index=True, max_length=30)),
                ('nombre_servicio', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(db_index=True, max_length=30)),
                ('entidad_codigo', models.CharField(blank=True, max_length=30)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('sede_nombre', models.CharField(blank=True, max_length=120)),
                ('sala_nombre', models.CharField(blank=True, max_length=120)),
                ('valor_servicio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='core.unidadnegocio')),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='atenciones.entidad')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'indexes': [models.Index(fields=['unidad_negocio', 'anio', 'mes', 'estado'], name='atenciones__unidad__155868_idx')],
            },
        ),
        migrations.CreateModel(
            name='TarifaConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_servicio', models.CharField(db_index=True, max_length=30, verbose_name='Código servicio (CUPS)')),
                ('nombre_servicio', models.CharField(blank=True, max_length=200)),
                ('tipo_contratacion', models.CharField(blank=True, max_length=60)),
                ('porcentaje', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor contratado')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='atenciones.entidad')),
            ],
            options={
                'verbose_name': 'Tarifa de convenio',
                'verbose_name_plural': 'Tarifas de convenios',
                'ordering': ['entidad', 'codigo_servicio'],
                'constraints': [models.UniqueConstraint(fields=('entidad', 'codigo_servicio'), name='uniq_tarifa_entidad_codigo')],
            },
        ),
    ]
