# Generated by Django 5.2.16 on 2026-07-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0001_initial'),
        ('core', '0003_alter_sede_options_sede_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_otras', models.BooleanField(default=False, help_text='Recoge además cualquier código sin asignar de la unidad.', verbose_name="Grupo residual ('Otras pruebas')")),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_servicio', to='core.unidadnegocio')),
            ],
            options={
                'verbose_name': 'Grupo de servicio',
                'verbose_name_plural': 'Grupos de servicio',
                'ordering': ['unidad_negocio', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoServicioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='atenciones.gruposervicio')),
            ],
            options={
                'verbose_name': 'Código de servicio del grupo',
                'verbose_name_plural': 'Códigos de servicio del grupo',
            },
        ),
        migrations.AddConstraint(
            model_name='gruposervicio',
            constraint=models.UniqueConstraint(fields=('unidad_negocio', 'nombre'), name='uniq_grupo_unidad_nombre'),
        ),
        migrations.AddConstraint(
            model_name='codigoserviciogrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'codigo'), name='uniq_codigo_por_grupo'),
        ),
    ]
